In [32]:
import pandas as pd

Starting Embedding

In [5]:
%cd ..

c:\MLOPS\Fake News Detection

c:\MLOPS\Fake News Detection\venv\Lib\site-packages\IPython\core\magics\osm.py:417: UserWarning: This is now an optional IPython functionality, setting dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]

In [33]:
data = pd.read_csv(r'Artifacts\21_39_29_11_2024\Data Validation\valid\valid_data.csv')

In [34]:
import gensim

In [35]:
from gensim.models import Word2Vec 
from gensim.utils import simple_preprocess

In [36]:
from nltk import sent_tokenize

In [37]:
data = data.drop(columns = ['title' , 'subject' , 'date'])

In [38]:
data.drop(columns = ['Unnamed: 0'] , inplace = True)

In [39]:
import nltk
import string
from nltk.corpus import stopwords

In [40]:
nltk.download('punkt')
nltk.download('stopwords')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\ayush\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ayush\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [41]:
punctuations = set(string.punctuation)
stop_words = set(stopwords.words('english'))

In [42]:
story = [ ]

In [43]:
data

                                                    text  reality
0      Donald Trump s White House is in chaos, and th...        1
1      Now that Donald Trump is the presumptive GOP n...        1
2      Mike Pence is a huge homophobe. He supports ex...        1
3      SAN FRANCISCO (Reuters) - California Attorney ...        1
4      Twisted reasoning is all that comes from Pelos...        1
...                                                  ...      ...
44893  ABUJA (Reuters) - The United States has formal...        1
44894  Tune in to the Alternate Current Radio Network...        1
44895   I m convinced the Freedom From Religion group...        1
44896  WASHINGTON (Reuters) - The Republican tax plan...        1
44897  SYDNEY (Reuters) - The U.N. High Commissioner ...        1

[44898 rows x 2 columns]

In [48]:
from gensim.utils import tokenize

In [80]:
for news in data.head()['text']:
    tokenized = tokenize(news.lower())
    story.append([word for word in tokenized if word not in stop_words and word not in punctuations])

In [81]:
import numpy as np

5

In [115]:
import gensim

In [116]:
model = gensim.models.Word2Vec(
    window = 3, 
    min_count = 2
)

In [117]:
model.build_vocab(story)

In [118]:
model.train(story , total_examples=model.corpus_count, epochs = model.epochs)

(6899, 8540)

In [128]:
type(model.wv.index_to_key)

list

In [126]:
words

array([-2.3885488e-03, -4.1914289e-03,  3.3983940e-03, -1.4833218e-04,
       -8.9964811e-03, -7.0110043e-03, -2.1997471e-03, -2.2367008e-03,
       -8.1213787e-03,  5.8333580e-03,  8.5383840e-03,  9.2668300e-03,
        3.0961100e-03, -9.3846228e-03, -3.0055421e-03,  7.3511833e-03,
       -4.5484765e-03, -3.6137640e-03,  2.9102713e-03,  8.9533161e-03,
        1.2792493e-03,  8.6964965e-03, -3.9375201e-03,  7.8636706e-03,
       -5.8239396e-03,  7.0941155e-03, -9.4609559e-03, -6.5383180e-03,
       -9.4423170e-04, -3.7820500e-05,  6.0196598e-03, -3.6116659e-03,
        1.9504860e-03,  1.9369201e-03, -1.4147852e-03,  7.1507427e-03,
       -1.6070367e-04,  3.6705183e-03, -5.1521799e-03,  7.9960615e-04,
       -3.0738015e-03,  4.2213057e-03, -4.3022363e-03,  6.0844412e-03,
       -6.0145659e-03,  2.5400051e-04,  8.8216141e-03,  2.4743499e-03,
       -6.6545713e-03,  4.3141880e-04,  8.3622234e-03, -7.0302691e-03,
       -9.5785623e-03, -7.8288130e-03, -8.4338058e-04,  9.7162873e-03,
       -2.9983560e-03, -4.5963377e-03, -4.3727448e-03,  1.4435290e-03,
       -4.8473864e-03,  6.3488656e-04, -4.7150464e-03, -1.0504561e-03,
       -8.3019055e-04,  1.5800772e-03,  5.6036059e-03,  1.0599565e-03,
        3.6114797e-03,  6.1579915e-03,  4.7516245e-03,  8.5780444e-03,
       -7.3161506e-04, -9.7732693e-03,  1.1028044e-03,  3.1239511e-03,
       -1.8125062e-03, -6.1334809e-03, -9.9989795e-04, -2.7807637e-03,
       -6.8773860e-03, -1.8106934e-03, -1.0052056e-02,  7.9140626e-03,
        7.4502435e-03,  7.6878415e-03, -4.0055839e-03,  5.2436972e-03,
        6.6645886e-03,  2.0134596e-04,  6.7546929e-04, -4.5297942e-03,
        6.7490195e-03,  8.8877846e-03, -4.2459187e-03,  9.4293812e-03,
        2.7061051e-03, -5.0010346e-03,  5.7682749e-03, -7.3960854e-04],
      dtype=float32)

In [136]:
sentence = "Donald Trump was about to be Killed"

In [137]:
tokenized = tokenize(sentence.lower())

In [138]:
embed = [ ]

In [139]:
tokenized

In [142]:
for words in tokenized:
    # print(words)
    if words in model.wv.index_to_key:
        embed.append(model.wv[words])
    else:
        embed.append([0] * model.vector_size)

In [143]:
sum(np.array(embed))

array([-3.10608640e-03,  3.36643634e-03,  2.89378269e-03, -2.07121286e-03,
        1.61019131e-02,  7.53865577e-04, -9.40811925e-03,  1.18912290e-02,
        3.69590055e-03, -2.32830499e-02,  1.82127166e-02, -1.71376317e-03,
       -1.12418032e-02,  1.07460656e-02,  1.51987560e-02,  1.06620037e-02,
        4.34676651e-03,  8.04078998e-03,  7.74814677e-03, -9.53402923e-03,
       -6.62184320e-03, -4.57854616e-03,  1.00582945e-02, -1.88926442e-02,
        2.10519107e-02, -5.02631086e-03, -1.72411720e-03,  6.37294259e-03,
        7.22932199e-03,  1.40005662e-02,  1.52647594e-02, -4.12349682e-03,
        4.21455139e-03, -1.89262079e-02,  8.90232564e-03,  5.57082728e-03,
        7.64639862e-03,  4.65359958e-03,  1.76509861e-02,  3.62962548e-03,
        3.59317870e-04, -8.21377384e-03, -1.14737886e-02, -9.17468875e-03,
        1.09327191e-02,  8.36364366e-03,  1.09881641e-02, -8.97192600e-03,
       -3.34322511e-03,  1.01811589e-02,  2.57423031e-03, -1.33009239e-02,
       -3.29922474e-03,  1.78657020e-02, -2.86457012e-04,  1.64143369e-03,
        1.28807788e-02,  1.48255029e-02, -1.28167487e-02,  1.44237214e-02,
       -1.81900717e-02,  1.23557551e-02,  8.33984558e-03,  6.46285759e-03,
       -7.20702088e-03,  1.53408549e-02,  1.59590484e-02, -1.29148597e-03,
        2.75665801e-03,  1.90196619e-02, -5.20848436e-03, -4.17787977e-03,
        1.56699666e-02,  6.29335153e-03, -2.77835404e-03, -2.11485014e-02,
       -4.42986842e-03,  3.17417738e-03,  3.00131820e-03, -6.29435759e-03,
       -4.17092908e-03,  6.66176225e-03,  8.01658817e-03, -5.84842404e-04,
        1.09115410e-02,  7.95240188e-03, -1.13177440e-03, -5.35055378e-03,
       -1.49570685e-03,  6.12866785e-03, -1.86940318e-03,  3.12119268e-03,
        6.89113513e-05, -9.41768632e-03, -9.77329118e-03,  5.11921803e-03,
        8.29060283e-03, -6.78333128e-03,  4.17815382e-03,  4.57601575e-03])

ZeroDivisionError: division by zero

In [144]:
for word in model['text']:
    word

                                                    text  reality
0      Donald Trump s White House is in chaos, and th...        1
1      Now that Donald Trump is the presumptive GOP n...        1
2      Mike Pence is a huge homophobe. He supports ex...        1
3      SAN FRANCISCO (Reuters) - California Attorney ...        1
4      Twisted reasoning is all that comes from Pelos...        1
...                                                  ...      ...
44893  ABUJA (Reuters) - The United States has formal...        1
44894  Tune in to the Alternate Current Radio Network...        1
44895   I m convinced the Freedom From Religion group...        1
44896  WASHINGTON (Reuters) - The Republican tax plan...        1
44897  SYDNEY (Reuters) - The U.N. High Commissioner ...        1

[44898 rows x 2 columns]